// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rank } from "./Rank";
import type { Suit } from "./Suit";

export interface Card { rank: Rank, suit: Suit, }