// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Card } from "./Card";

export interface PlayerView { player_hand: Array<Card | null>, active_cards: Array<Card | null>, opponent_hand: Array<boolean>, opponent_pile: boolean, middle_piles: Array<boolean>, }