// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerView } from "./PlayerView";
import type { ServerAction } from "./ServerAction";

export interface ServerMessage { action: ServerAction, player_view: PlayerView, }